name: Build and Test React frontend
on:
  push:
    paths:
      - .github/workflows/frontend-build-test.yml
      - frontend/**
  pull_request:
    paths:
      - frontend/**

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 15.x
        uses: actions/setup-node@v4
        with:
          node-version: 15.x
      - name: npm ci, build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
  
  test:
    needs: build
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 15.x
        uses: actions/setup-node@v4
        with:
          node-version: 15.x
      - name: npm ci, build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
          npm test   
