name: Build and Test React Application

# Controls when the action will run. 
on:
  push:
    paths:
      - .github/workflows/**
      - frontend/**
  pull_request:
    paths:
      - .github/workflows/**
      - frontend/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: npm ci, build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
  
  test:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: npm ci, build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
          npm test   
